[package]
name = "franca"
version = "0.1.0"
edition = "2021"

[lib]
name = "franca"
path = "src/lib.rs"

[[bin]]
name = "franca-transform"
path = "src/bin.rs"

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.37", features = ["full"] }
